FROM node:20 AS builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./ /usr/src/app/

RUN npm install -g npm@10.2.5
RUN npm install
RUN npm run build

FROM nginx:1.25.2

COPY --from=builder /usr/src/app/dist /usr/share/ngninx/html
COPY ./default.conf /etc/nginx/conf.d/
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]